In [1]:
import quarters_clean

In [3]:
gov_expenditure_df = quarters_clean.pd.read_parquet("../parquet_exports/government_expenditure_values.parquet")

In [4]:
gov_expenditure_df.head()

,Quarter,Year,Australia,Austria,Belgium,Brazil,Bulgaria,Canada,Chile,Colombia,...,South-Africa,South-Korea,Spain,Sweden,Switzerland,Thailand,Turkey,USA,United-Kingdom,Paraguay
0,1,1960,0.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,9.43,NaN,NaN,NaN,NaN,NaN,29.35,1.02,NaN
1,2,1960,0.49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,8.79,NaN,NaN,NaN,NaN,NaN,29.73,1.05,NaN
2,3,1960,0.46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,8.35,NaN,NaN,NaN,NaN,NaN,30.73,1.05,NaN
3,4,1960,0.51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,9.00,NaN,NaN,NaN,NaN,NaN,31.23,1.08,NaN
4,1,1961,0.48,NaN,NaN,NaN,NaN,1.75,NaN,NaN,...,NaN,9.81,NaN,NaN,NaN,NaN,NaN,31.70,1.12,NaN

In [5]:
gov_expenditure_df.tail()

,Quarter,Year,Australia,Austria,Belgium,Brazil,Bulgaria,Canada,Chile,Colombia,...,South-Africa,South-Korea,Spain,Sweden,Switzerland,Thailand,Turkey,USA,United-Kingdom,Paraguay
257,2,2024,156.31,27.03,37.45,545.21,9.65,161.12,11818.46,62335.87,...,345.79,114008.8,79.09,421.86,23.78,744.67,1465.73,1235.75,147.51,9957.51
258,3,2024,155.21,26.19,34.95,535.10,9.65,165.91,11518.06,58028.78,...,354.34,108693.2,72.50,414.51,23.95,856.67,1618.97,1258.75,149.82,10463.28
259,4,2024,161.47,28.77,39.64,660.17,11.59,173.31,12467.10,86802.11,...,362.05,111135.2,85.91,453.26,24.27,790.15,1947.17,1274.93,156.07,12498.37
260,1,2025,157.62,26.20,37.32,517.27,9.55,179.13,12137.12,51936.80,...,351.54,118271.4,73.77,412.74,24.36,747.59,1884.21,1287.48,157.65,9983.01
261,2,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,81.73,NaN,NaN,NaN,NaN,1297.43,NaN,NaN

In [6]:
quarters_clean.summarize_missing_by_country(gov_expenditure_df)

                Missing Count  Missing %
India                     206      78.63
Malaysia                  189      72.14
Macedonia                 161      61.45
Colombia                  161      61.45
Turkey                    153      58.40
Chile                     145      55.34
Brazil                    145      55.34
Russia                    143      54.58
Israel                    141      53.82
Ireland                   141      53.82
Czech-Republic            141      53.82
Cyprus                    141      53.82
Hungary                   141      53.82
Iceland                   141      53.82
Greece                    141      53.82
Estonia                   141      53.82
Latvia                    141      53.82
Italy                     141      53.82
Lithuania                 141      53.82
Luxembourg                141      53.82
Bulgaria                  141      53.82
Belgium                   141      53.82
Croatia                   141      53.82
Austria                   141      53.82
Portugal                  141      53.82
Switzerland               141      53.82
Slovakia                  141      53.82
Slovenia                  141      53.82
Romania                   141      53.82
Serbia                    141      53.82
Malta                     141      53.82
Poland                    141      53.82
Netherlands               140      53.44
Spain                     140      53.44
Paraguay                  137      52.29
Japan                     137      52.29
Mexico                    134      51.15
Thailand                  133      50.76
South-Africa              133      50.76
Sweden                    133      50.76
Denmark                   125      47.71
Germany                   125      47.71
New-Zealand               121      46.18
Hong-Kong                 121      46.18
Finland                   121      46.18
Indonesia                 121      46.18
Philippines                84      32.06
Peru                       81      30.92
France                     80      30.53
Norway                     73      27.86
Singapore                  61      23.28
Canada                      5       1.91
Australia                   1       0.38
South-Korea                 1       0.38
United-Kingdom              1       0.38
USA                         0       0.00

**H1)** The previous output indicates that India will be the country that will most restrict us in the time range available to perform the correlation analysis. This statement is only correct due to the process of extracting and joining the values of this indicator. If indicators were downloaded for a country and those values were not available for a time range already existing in the master data frame, NaN values were assigned.

**T1)** The important thing is to first cross-reference the countries available in the house price index with the countries available in this data frame in such a way as to concentrate the work on the countries that will be available and then find a similarity with Paraguay.|