In [1]:
import quarters_clean

In [2]:
investment_growth_df = quarters_clean.pd.read_parquet("../parquet_exports/investment_growth_values.parquet")

In [3]:
investment_growth_df.head()

,Quarter,Year,Australia,Austria,Belgium,Brazil,Bulgaria,Canada,Chile,Colombia,...,South-Africa,South-Korea,Spain,Sweden,Switzerland,Thailand,Turkey,USA,United-Kingdom,Paraguay
0,1,1961,1.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,23.29,NaN,NaN,NaN,NaN,NaN,-5.16,15.46,NaN
1,2,1961,-1.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,12.22,NaN,NaN,NaN,NaN,NaN,-1.91,15.49,NaN
2,3,1961,1.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,26.66,NaN,NaN,NaN,NaN,NaN,2.68,13.40,NaN
3,4,1961,-3.37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,50.41,NaN,NaN,NaN,NaN,NaN,6.23,6.95,NaN
4,1,1962,0.41,NaN,NaN,NaN,NaN,6.56,NaN,NaN,...,NaN,25.56,NaN,NaN,NaN,NaN,NaN,9.64,3.55,NaN

In [4]:
investment_growth_df.tail()

,Quarter,Year,Australia,Austria,Belgium,Brazil,Bulgaria,Canada,Chile,Colombia,...,South-Africa,South-Korea,Spain,Sweden,Switzerland,Thailand,Turkey,USA,United-Kingdom,Paraguay
253,2,2024,5.04,0.54,2.71,9.21,0.76,2.08,5.66,3.23,...,0.55,1.06,3.59,2.29,0.06,-5.44,73.99,5.59,3.19,9.12
254,3,2024,5.63,2.25,-0.95,15.82,5.01,2.56,7.34,23.91,...,1.19,0.61,3.74,2.73,-0.19,6.34,44.34,5.93,6.20,9.06
255,4,2024,5.54,1.74,7.57,15.61,9.27,6.53,11.37,45.43,...,0.12,0.74,8.72,3.82,1.07,4.92,45.85,4.54,4.70,12.06
256,1,2025,5.85,1.38,4.23,16.50,11.23,5.13,7.81,18.72,...,-1.34,-1.58,7.33,-1.19,1.66,5.13,30.21,4.87,7.14,17.00
257,2,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,6.92,NaN,NaN,NaN,NaN,3.88,NaN,NaN

In [5]:
quarters_clean.summarize_missing_by_country(investment_growth_df)

                Missing Count  Missing %
Malaysia                  189      73.26
India                     178      68.99
Colombia                  161      62.40
Turkey                    153      59.30
Brazil                    145      56.20
Russia                    143      55.43
Bulgaria                  141      54.65
Ireland                   141      54.65
Hungary                   141      54.65
Greece                    141      54.65
Croatia                   141      54.65
Estonia                   141      54.65
Iceland                   141      54.65
Czech-Republic            141      54.65
Portugal                  141      54.65
Italy                     141      54.65
Latvia                    141      54.65
Lithuania                 141      54.65
Luxembourg                141      54.65
Israel                    141      54.65
Cyprus                    141      54.65
Belgium                   141      54.65
Austria                   141      54.65
Romania                   141      54.65
Switzerland               141      54.65
Slovakia                  141      54.65
Slovenia                  141      54.65
Malta                     141      54.65
Serbia                    141      54.65
Poland                    141      54.65
Netherlands               140      54.26
Spain                     140      54.26
Paraguay                  137      53.10
Mexico                    134      51.94
South-Africa              133      51.55
Sweden                    133      51.55
Thailand                  133      51.55
Denmark                   125      48.45
Germany                   125      48.45
Finland                   121      46.90
Chile                     121      46.90
Indonesia                 121      46.90
Hong-Kong                 117      45.35
New-Zealand               110      42.64
Philippines                85      32.95
Peru                       81      31.40
France                     80      31.01
Norway                     73      28.29
Singapore                  61      23.64
Canada                      5       1.94
Australia                   1       0.39
Japan                       1       0.39
South-Korea                 1       0.39
United-Kingdom              1       0.39
USA                         0       0.00

**H1)** The previous output indicates that Malaysia will be the country that will most restrict us in the time range available to perform the correlation analysis. This statement is only correct due to the process of extracting and joining the values of this indicator. If indicators were downloaded for a country and those values were not available for a time range already existing in the master data frame, NaN values were assigned.

In [6]:
missing_entries = quarters_clean.get_missing_entries(investment_growth_df)
missing_entries.head()

   Quarter  Year   Country  Value
0        1  1961   Austria    NaN
1        1  1961   Belgium    NaN
2        1  1961    Brazil    NaN
3        1  1961  Bulgaria    NaN
4        1  1961    Canada    NaN

In [7]:
malaysia_missing = quarters_clean.clean_country_missing_entries(missing_entries, "Malaysia")
malaysia_missing

     Quarter  Year   Country  Value
0          1  1961  Malaysia    NaN
1          2  1961  Malaysia    NaN
2          3  1961  Malaysia    NaN
3          4  1961  Malaysia    NaN
4          1  1962  Malaysia    NaN
..       ...   ...       ...    ...
184        1  2007  Malaysia    NaN
185        2  2007  Malaysia    NaN
186        3  2007  Malaysia    NaN
187        4  2007  Malaysia    NaN
188        2  2025  Malaysia    NaN

[189 rows x 4 columns]

The previous outputs show us that Malaysia has no values for the investment growth from 1961 to 2007 nor for 2025. Consequently, it has values in the range from 2008 to 2024, a desirable range since other values which we extracted with the crawlers are defined between 2014 and 2023.

### Let's delete all the data from the beginning until 2007 and just 2025

In [8]:
clean_df1 = investment_growth_df.copy()

In [9]:
clean_df1 = quarters_clean.filter_by_year(clean_df1, min_year=2007, max_year=2024, exclude_years=[2025])
clean_df1.head()

,Quarter,Year,Australia,Austria,Belgium,Brazil,Bulgaria,Canada,Chile,Colombia,...,South-Africa,South-Korea,Spain,Sweden,Switzerland,Thailand,Turkey,USA,United-Kingdom,Paraguay
0,1,2008,9.85,4.99,10.28,21.15,20.39,5.87,18.69,1.48,...,18.31,6.21,1.87,7.64,3.55,14.66,16.77,-2.56,4.66,30.69
1,2,2008,13.21,7.73,10.23,23.97,54.46,5.41,31.55,3.45,...,25.24,7.49,-1.07,4.65,4.12,11.25,16.93,-4.10,2.41,38.51
2,3,2008,11.80,4.20,4.77,29.99,40.69,6.61,39.22,15.51,...,30.82,13.84,-3.72,5.48,3.50,13.19,3.55,-5.94,1.51,32.64
3,4,2008,8.69,3.94,0.14,17.29,22.36,4.57,27.18,31.95,...,30.68,7.87,-11.23,1.31,-0.97,5.66,-2.43,-10.83,-6.75,8.32
4,1,2009,1.55,-1.60,-5.54,1.94,-4.30,-9.68,1.43,4.98,...,14.28,6.20,-17.88,-9.31,-6.83,-20.50,-25.34,-16.86,-8.63,-7.55

In [10]:
clean_df1.tail()

,Quarter,Year,Australia,Austria,Belgium,Brazil,Bulgaria,Canada,Chile,Colombia,...,South-Africa,South-Korea,Spain,Sweden,Switzerland,Thailand,Turkey,USA,United-Kingdom,Paraguay
63,4,2023,10.18,0.27,1.30,-3.14,21.03,3.03,-3.21,-30.04,...,7.12,-0.75,7.26,5.57,-0.12,-1.85,92.75,9.26,4.13,2.66
64,1,2024,7.72,-1.30,1.19,4.62,2.90,3.05,3.80,-9.62,...,4.64,3.32,4.90,2.02,-2.18,-4.14,90.53,9.28,1.08,4.09
65,2,2024,5.04,0.54,2.71,9.21,0.76,2.08,5.66,3.23,...,0.55,1.06,3.59,2.29,0.06,-5.44,73.99,5.59,3.19,9.12
66,3,2024,5.63,2.25,-0.95,15.82,5.01,2.56,7.34,23.91,...,1.19,0.61,3.74,2.73,-0.19,6.34,44.34,5.93,6.20,9.06
67,4,2024,5.54,1.74,7.57,15.61,9.27,6.53,11.37,45.43,...,0.12,0.74,8.72,3.82,1.07,4.92,45.85,4.54,4.70,12.06

In [11]:
quarters_clean.summarize_missing_by_country(clean_df1)

                Missing Count  Missing %
Russia                      1       1.47
Austria                     0       0.00
Australia                   0       0.00
Brazil                      0       0.00
Bulgaria                    0       0.00
Canada                      0       0.00
Belgium                     0       0.00
Colombia                    0       0.00
Croatia                     0       0.00
Cyprus                      0       0.00
Czech-Republic              0       0.00
Denmark                     0       0.00
Estonia                     0       0.00
Finland                     0       0.00
France                      0       0.00
Germany                     0       0.00
Greece                      0       0.00
Hong-Kong                   0       0.00
Hungary                     0       0.00
Iceland                     0       0.00
India                       0       0.00
Indonesia                   0       0.00
Chile                       0       0.00
Ireland                     0       0.00
Israel                      0       0.00
Japan                       0       0.00
Italy                       0       0.00
Lithuania                   0       0.00
Luxembourg                  0       0.00
Malaysia                    0       0.00
Latvia                      0       0.00
Mexico                      0       0.00
Netherlands                 0       0.00
New-Zealand                 0       0.00
Norway                      0       0.00
Peru                        0       0.00
Philippines                 0       0.00
Poland                      0       0.00
Malta                       0       0.00
Portugal                    0       0.00
Romania                     0       0.00
Serbia                      0       0.00
Singapore                   0       0.00
Slovakia                    0       0.00
Slovenia                    0       0.00
South-Africa                0       0.00
South-Korea                 0       0.00
Spain                       0       0.00
Sweden                      0       0.00
Switzerland                 0       0.00
Thailand                    0       0.00
Turkey                      0       0.00
USA                         0       0.00
United-Kingdom              0       0.00
Paraguay                    0       0.00

In [12]:
clean_df1["Russia"] = clean_df1["Russia"].ffill()

In [13]:
quarters_clean.summarize_missing_by_country(clean_df1)

                Missing Count  Missing %
Australia                   0        0.0
Austria                     0        0.0
Belgium                     0        0.0
Brazil                      0        0.0
Bulgaria                    0        0.0
Canada                      0        0.0
Chile                       0        0.0
Colombia                    0        0.0
Croatia                     0        0.0
Cyprus                      0        0.0
Czech-Republic              0        0.0
Denmark                     0        0.0
Estonia                     0        0.0
Finland                     0        0.0
France                      0        0.0
Germany                     0        0.0
Greece                      0        0.0
Hong-Kong                   0        0.0
Hungary                     0        0.0
Iceland                     0        0.0
India                       0        0.0
Indonesia                   0        0.0
Ireland                     0        0.0
Israel                      0        0.0
Italy                       0        0.0
Japan                       0        0.0
Latvia                      0        0.0
Lithuania                   0        0.0
Luxembourg                  0        0.0
Malaysia                    0        0.0
Malta                       0        0.0
Mexico                      0        0.0
Netherlands                 0        0.0
New-Zealand                 0        0.0
Norway                      0        0.0
Peru                        0        0.0
Philippines                 0        0.0
Poland                      0        0.0
Portugal                    0        0.0
Romania                     0        0.0
Russia                      0        0.0
Serbia                      0        0.0
Singapore                   0        0.0
Slovakia                    0        0.0
Slovenia                    0        0.0
South-Africa                0        0.0
South-Korea                 0        0.0
Spain                       0        0.0
Sweden                      0        0.0
Switzerland                 0        0.0
Thailand                    0        0.0
Turkey                      0        0.0
USA                         0        0.0
United-Kingdom              0        0.0
Paraguay                    0        0.0

In [14]:
clean_df2 = clean_df1.copy()

In [15]:
clean_df2 = quarters_clean.average_by_year(clean_df2)

   Year  Australia  Austria  Belgium   Brazil  Bulgaria   Canada    Chile  \
0  2008    10.8875   5.2150   6.3550  23.1000   34.4750   5.6150  29.1600
1  2009    -1.1950  -5.3875  -7.4875   5.5100  -14.4225  -9.8450 -12.7825
2  2010     4.3450  -1.0975   1.5450  26.0275  -19.7350  11.4075  34.2475
3  2011     7.8600   8.8500   8.3325  13.2650    8.0025   6.7775  17.8600
4  2012    10.2100   3.8450   2.7425  10.6075    2.7550   7.3400  15.7150

   Colombia  Croatia  ...  South-Africa  South-Korea    Spain  Sweden  \
0   13.0975  13.5375  ...       26.2625       8.8525  -3.5375  4.7700
1   -2.0425 -14.6575  ...       -2.5925       4.1325 -19.7200 -9.9275
2    8.1350 -16.1800  ...       -1.3475       7.6275  -5.1375  6.4575
3   19.4750  -3.2975  ...       10.3775       4.7350  -8.5775  6.5375
4    3.5025  -3.8550  ...        8.0100       2.0600  -9.9850 -0.0025

   Switzerland  Thailand   Turkey      USA  United-Kingdom  Paraguay
0       2.5500   11.1900   8.7050  -5.8575          0.4575   27.5400
1      -7.4150  -13.0400 -16.5175 -17.4925        -11.0725    1.0725
2       3.4325   16.4600  27.7475   0.7950          3.3925   34.9625
3       3.1800   12.8350  36.4825   7.7575          1.1500    8.0975
4       4.1900   14.3175  10.3175  11.5425          3.3900   -3.0250

[5 rows x 56 columns]