In [11]:
import pandas as pd
import matplotlib.pyplot as plt

In [22]:
unemployment_df = pd.read_parquet("../parquet_exports/unemployment_rates_values_error.parquet")

In [23]:
unemployment_df.head()

,Quarter,Year,Australia,Austria,Belgium,Brazil,Bulgaria,Canada,Chile,China,...,South-Africa,South-Korea,Spain,Sweden,Switzerland,Thailand,Turkey,USA,United-Kingdom,Paraguay
0,Q1,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.8,1.6,NaN
1,Q1,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.2,1.7,NaN
2,Q1,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.4,1.6,NaN
3,Q1,1961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.9,1.3,NaN
4,Q1,1961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.6,1.3,NaN

In [24]:
unemployment_df.tail()

,Quarter,Year,Australia,Austria,Belgium,Brazil,Bulgaria,Canada,Chile,China,...,South-Africa,South-Korea,Spain,Sweden,Switzerland,Thailand,Turkey,USA,United-Kingdom,Paraguay
781,None,2021,4.87,5.8,6.0,14.2,5.1,7.4,9.50,NaN,...,NaN,3.8,15.1,10.5,4.8,NaN,10.4,5.9,4.6,NaN
782,None,2022,3.50,4.0,5.6,9.3,4.2,4.7,7.81,NaN,...,NaN,3.0,12.4,8.6,3.9,NaN,9.7,3.6,3.6,NaN
783,None,2023,3.40,4.7,5.3,8.0,4.5,5.2,8.53,NaN,...,NaN,2.7,11.4,9.3,3.7,NaN,9.0,3.6,4.3,NaN
784,None,2024,3.91,4.8,5.3,6.9,3.9,6.2,8.35,NaN,...,NaN,2.9,11.1,9.4,4.0,NaN,8.9,4.1,4.2,NaN
785,None,2025,4.19,5.5,6.3,5.8,3.7,6.5,NaN,NaN,...,NaN,2.8,10.0,9.4,NaN,NaN,NaN,4.1,NaN,NaN

In [25]:
private_credit_df = pd.read_parquet("../parquet_exports/private_credit_values_error.parquet")

In [26]:
private_credit_df.head()

,Quarter,Year,Australia,Austria,Belgium,Brazil,Bulgaria,Canada,Chile,China,...,South-Africa,South-Korea,Spain,Sweden,Switzerland,Thailand,Turkey,USA,United-Kingdom,Paraguay
0,Q1,1965,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Q2,1965,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Q2,1965,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Q3,1965,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Q3,1965,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
private_credit_df.tail()

,Quarter,Year,Australia,Austria,Belgium,Brazil,Bulgaria,Canada,Chile,China,...,South-Africa,South-Korea,Spain,Sweden,Switzerland,Thailand,Turkey,USA,United-Kingdom,Paraguay
719,Q1,2025,3450.54,NaN,414.51,6464.02,96.24,6527.35,232818.26,253483.65,...,4439.80,3396694.2,1124.92,7992.76,1371.22,20480.59,12644.87,10349.37,2130.12,177296.00
720,Q1,2025,3485.57,NaN,405.23,6578.51,97.86,6560.71,234811.72,257905.04,...,4556.08,3407758.8,1132.79,8017.75,1378.72,20534.05,13562.58,10352.49,2148.50,183935.62
721,Q2,2025,3510.04,NaN,NaN,6621.58,98.70,NaN,235884.82,257960.23,...,4534.67,NaN,NaN,NaN,NaN,20508.96,14106.37,10406.42,2146.74,184992.71
722,Q2,2025,3527.27,NaN,NaN,6655.38,99.88,NaN,236240.60,258530.46,...,4561.92,NaN,NaN,NaN,NaN,NaN,14601.68,NaN,NaN,NaN
723,None,2025,3552.83,NaN,NaN,6685.66,101.26,NaN,236137.51,260873.20,...,4622.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
cpi_df = pd.read_parquet("../parquet_exports/cpi_values_error.parquet")

In [29]:
cpi_df.head()

,Quarter,Year,Australia,Austria,Belgium,Brazil,Bulgaria,Canada,Chile,China,...,South-Africa,South-Korea,Spain,Sweden,Switzerland,Thailand,Turkey,USA,United-Kingdom,Paraguay
0,Q1,1960,NaN,NaN,NaN,NaN,NaN,15.5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.41,NaN,NaN
1,Q1,1960,NaN,NaN,NaN,NaN,NaN,15.5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.37,NaN,NaN
2,Q1,1960,NaN,NaN,NaN,NaN,NaN,15.4,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.41,NaN,NaN
3,Q2,1960,NaN,NaN,NaN,NaN,NaN,15.5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.54,NaN,NaN
4,Q2,1960,NaN,NaN,NaN,NaN,NaN,15.5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.57,NaN,NaN

In [30]:
cpi_df.tail()

,Quarter,Year,Australia,Austria,Belgium,Brazil,Bulgaria,Canada,Chile,China,...,South-Africa,South-Korea,Spain,Sweden,Switzerland,Thailand,Turkey,USA,United-Kingdom,Paraguay
782,Q1,2025,NaN,138.27,135.71,7245.38,142.53,163.5,107.70,131.6965,...,101.6,116.29,125.66,131.19,106.86,NaN,1133.49,319.799,136.1,138.2
783,Q2,2025,NaN,138.64,134.79,7276.54,140.76,163.4,107.91,131.8282,...,101.9,116.38,126.44,131.50,107.61,NaN,1167.42,320.795,137.7,NaN
784,Q2,2025,NaN,138.40,134.67,7295.46,140.84,NaN,108.12,131.5645,...,102.1,116.27,126.40,131.96,107.40,NaN,1185.16,321.465,138.0,NaN
785,Q3,2025,NaN,138.81,134.22,NaN,NaN,NaN,NaN,NaN,...,NaN,116.52,126.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN
786,None,2025,NaN,138.76,135.32,7312.97,141.44,NaN,107.68,131.4329,...,102.4,116.31,127.27,132.71,107.66,NaN,1201.39,322.561,138.4,NaN